id: A5845DC8F
base_file: f2D30.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:01:27.287133
  last_modified_at: 2022-06-05 20:01:27.287139
